<?php

declare(strict_types=1);

namespace Rehla\Core\Errors;

enum ErrorCode: string
{
    case INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE';
    case SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE';
    case PRICE_CHANGED = 'PRICE_CHANGED';
    case FORM_VERSION_CHANGED = 'FORM_VERSION_CHANGED';
    case DUPLICATE_PASSPORT = 'DUPLICATE_PASSPORT';
    case TRANSACTION_REFERENCE_USED = 'TRANSACTION_REFERENCE_USED';
    case IDEMPOTENCY_KEY_REUSED = 'IDEMPOTENCY_KEY_REUSED';
    case OPERATION_IN_PROGRESS = 'OPERATION_IN_PROGRESS';
    case DOCUMENT_NOT_CLEAN = 'DOCUMENT_NOT_CLEAN';
    case FORBIDDEN_RESOURCE = 'FORBIDDEN_RESOURCE';
}
